### ISSUE TITLE
Add Localization

### ISSUE THREAD

**Issue by ralphwilliams** [ralphwilliams/DNNVideoCourseModule#13]
Add Localization

**Comment by WillStrohl** [comment]
Is it done yet?

**Comment by ralphwilliams** [comment]
no

**Comment by WillStrohl** [comment]
How about now?

**Comment by david-poindexter** [comment]
LOL - really?

**Comment by ralphwilliams** [comment]
Tried adding localization, but not able to figure out how to deal with nested view files.

**Comment by david-poindexter** [comment]
Are you using ngRoute w/ ngInclude or ui-router?

**Comment by ralphwilliams** [comment]
I'm using ngRoute but I don't think I'm using ngInclude or ui-router. It's been a while since I did this and I have forgotten about 63% of what I did ;)

The issue I'm having is that I don't really understand the localization part very well. Every example that I have seen has put the resx file in the App_LocalResources folder at the root level. And all of the controllers are at the root level. However, my HTML template files are nested in a couple of layers.

**Comment by david-poindexter** [comment]
@ralphwilliams it is my understanding that it works like this...
With the exception of ModuleAction (which includes a "localResourceFile" to specify the file used for the titleKey field), DNN will pull Resx values from the resource file in App_LocalResources that matches the name of the HMTL view you are calling it from (regardless of where it is within your module folder structure).  So, if you were to going to use the following within the View.html file,...

```
[Resx:{key:"MyItem"}]
```

...DNN would look for the value of MyItem within the View.resx file found in the App_LocalResources folder.

In the case of ModuleAction, you can use something like the following:

```
[ModuleAction:{controlKey : "Edit", securityAccessLevel : "Edit",  titleKey: "EditModule", localResourceFile: "~/DesktopModules/MyModule/App_LocalResources/View.resx" }]
```

Hope this helps!

**Comment by ralphwilliams** [comment]
Thanks, I tried that and it didn't seem to work. I was able to get it to work on my html file that is set up for my view, but not in the angular html template files. I might reach out to Joe tomorrow about it. For example, this file https://github.com/ralphwilliams/DNNVideoCourseModule/blob/master/ng/Views/videoListView.html

**Comment by david-poindexter** [comment]
I have not had much of a chance to play with this, but will let you know if I figure it out.  My assumptions may have been incorrect.  Perhaps since everything is being rendered within the context of View.html, then all localization would need to be in the one View.resx file?  That would kinda suck in a more complex app, but may work for your situation.  Have you tried that approach?

**Comment by ralphwilliams** [comment]
Followed Peter Donker's approach by creating a webservice as seen here: https://github.com/DNN-Connect/Map/blob/master/Controllers/ModuleController.cs
