### ISSUE TITLE
Packages folder is missing from the source

### ISSUE THREAD

**Issue by WillStrohl** [ralphwilliams/DNNVideoCourseModule#4]
Release packages can't be built, because the Packages folder that has dependent MSBuild information is missing.  You get this error:

The "MSBuild.Community.Tasks.XmlRead" task could not be loaded from the assembly C:\Websites\platform730\Website\DesktopModules\Calvary_VideoCourse\packages\MSBuildTasks.1.4.0.88\tools\MSBuild.Community.Tasks.dll. Could not load file or assembly 'file:///C:\Websites\platform730\Website\DesktopModules\Calvary_VideoCourse\packages\MSBuildTasks.1.4.0.88\tools\MSBuild.Community.Tasks.dll' or one of its dependencies. The system cannot find the file specified. Confirm that the <UsingTask> declaration is correct, that the assembly and all its dependencies are available, and that the task contains a public class that implements Microsoft.Build.Framework.ITask.

![2015-09-18_1721](https://cloud.githubusercontent.com/assets/938023/9973554/d165b4dc-5e29-11e5-954d-ff15d6686b3a.png)

**Comment by ralphwilliams** [comment]
@hismightiness When you get a chance, can you please verify this fix?
