### ISSUE TITLE
Add DNN Antiforgery and Authentication into webservices

### ISSUE THREAD

**Issue by ralphwilliams** [ralphwilliams/DNNVideoCourseModule#7]
Update the webservices to use DNN's Antiforgery and Authentication

**Comment by WillStrohl** [comment]
Examples for your convenience:

https://github.com/hismightiness/dnnextensions/blob/CodeCampModule/Modules/CodeCamp/Scripts/ng/factories/codeCampServiceFactory.js

https://github.com/hismightiness/dnnextensions/blob/CodeCampModule/Modules/CodeCamp/Default.ascx
